# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'
networks:
  assistant:
    name: app
  # driver: bridge
volumes:
  postgres-data:
# Define services
services:
  #######################
  # App backend service #
  #######################
  #assistant-app:
  # build:
  #  context: assistant-app
  # dockerfile: src/main/docker/Dockerfile
  # Give the container the name web-app. You can changes to something else.
  #container_name: assistant-app
  # Forward the exposed port 8080 on the container to port 8080 on the host machine
  #ports:
  # - "8088:8088"
  #networks:
  # - assistant
  # This service depends on postgres. Start that first.
  #depends_on:
  # - assistant-db
  ###############################
  # Database Service (Postgres) #
  ###############################
  assistant-db:
    build:
      context: assistant-db
      dockerfile: src/main/docker/Dockerfile
    container_name: assistant-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - assistant
    ports:
      - "5444:5432"
    restart: always
  ################################
  # Database Service (liquibase) #
  ################################
  assistant-migrations:
    image: kilna/liquibase-postgres
    container_name: liquibase
    depends_on:
      - assistant-db
    volumes:
      - ./assistant-db/src/main/resources/db:/db
    networks:
      - assistant
    environment:
      LIQUIBASE_DATABASE: it
      LIQUIBASE_CHANGELOG: /db/database_changelog.xml
      LIQUIBASE_USERNAME: ms_assistant
      LIQUIBASE_PASSWORD: ms_assistant
      LIQUIBASE_HOST: assistant-db
    command:
      - bash
      - -c
      - |
        set -e
        echo "waiting for the db to be available"
        until nc -z $$LIQUIBASE_HOST $$LIQUIBASE_PORT; do
        echo "the db is not available - sleeping"
        sleep 1
        done
        echo "the db is up"
        liquibase update
