# Spring Boot configuration
spring:
  # Database
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/it?curentSchema=ms_assistant
    username: ms_assistant
    password: ms_assistant
  # JPA properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none #so that Hibernate does not perform any modification actions
    show-sql: false

  liquibase:
    enabled: false
    change-log: classpath:db\database_changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

# Server configuration
server:
  port: 8080

